version: '3'
services:
  
  nginx:
    container_name: nginx_app
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "../:/var/www/app"
    restart: always
    links:
      - php
    networks:
      - default  
  php:
    container_name: php_app
    build: ./php
    volumes:
      - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../:/var/www/app"
    restart: always
    expose:
      - "9000"
    links:
      - mysql
    networks:
      - default  
  
  mysql:
    container_name: mysql_app
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: app
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    driver: bridge
