DROP TABLE IF EXISTS sale_products;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS costumers;
DROP TABLE IF EXISTS product_images;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS admins;